#!/bin/sh

# This file allows you to execute commands at the beginning
# of the X user session - before the window manager is started.
# The xprofile file is similar in style to xinitrc.

XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}

[ -r "$HOME/.profile" ] && . "$HOME/.profile"

# run all system xinitrc shell scripts.
if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for file in /etc/X11/xinit/xinitrc.d/* ; do
		[ -x "$file" ] && . "$file"
	done
	unset file
fi

[ -x "$(command -v xrdb)" ] && xrdb "$XDG_CONFIG_HOME/x11/xresources" &
[ -x "$(command -v slstatus)" ] && slstatus &
[ -x "$(command -v remaps)" ] && remaps &
[ -x "$(command -v sxhkd)" ] && sxhkd &
[ -x "$(command -v setbg)" ] && setbg &
[ -x "$(command -v dunst)" ] && dunst &
[ -x "$(command -v syncthing)" ] && syncthing serve --no-browser --logfile=default &
[ -x "$(command -v unclutter)" ] && unclutter &
[ -x "$(command -v setxkbmap)" ] && setxkbmap -layout us,fr,ar -option grp:alt_shift_toggle &
[ -x "$(command -v nm-applet)" ] && nm-applet &
