#!/bin/bash

XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}

n ()
{
	local documentsPath
	documentsPath="$(xdg-user-dir DOCUMENTS)"
	local downloadsPath
	downloadsPath="$(xdg-user-dir DOWNLOAD)"
	local moviesPath
	moviesPath="$(xdg-user-dir MOVIES)"
	local projectsPath
	projectsPath="$(xdg-user-dir PROJECTS)"

	local BLK="03"
	local CHR="03"
	local DIR="04"
	local EXE="02"
	local REG="00"
	local HARDLINK="00"
	local SYMLINK="06"
	local MISSING="00"
	local ORPHAN="01"
	local FIFO="03"
	local SOCK="05"
	local OTHER="00"

	# Block nesting of nnn in subshells
	if [[ "${NNNLVL:-0}" -ge 1 ]]; then
		echo "nnn is already running"
		return
	fi

	# The behaviour is set to cd on quit (nnn checks if NNN_TMPFILE is set)
	# If NNN_TMPFILE is set to a custom path, it must be exported for nnn to
	# see. To cd on quit only on ^G, remove the "export" and make sure not to
	# use a custom path, i.e. set NNN_TMPFILE *exactly* as follows:
	#     NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"
	export NNN_TMPFILE="$XDG_CONFIG_HOME/nnn/.lastd"

	NNN_TRASH=1 \
		NNN_FIFO='/tmp/nnn.fifo' \
		NNN_ARCHIVE="\\.(rar|zip|tar)$" \
		NNN_FCOLORS="$BLK$CHR$DIR$EXE$REG$HARDLINK$SYMLINK$MISSING$ORPHAN$FIFO$SOCK$OTHER" \
		NNN_OPENER="open" \
		NNN_COLORS='#0c020b09;4216' \
		NNN_PLUG="p:preview-tui;t:preview-tabbed;n:bulknew;e:preview-tui-ext;c:cleanfilename;m:mtpmount;w:nmount;l:finder" \
		NNN_BMS="d:$documentsPath;D:$downloadsPath;s:~/Programming/thirdparty/;b:~/.local/bin;c:~/C/;C:~/.config/;l:~/.local/share/;u:~/university/smi_s4;m:$moviesPath;p:$projectsPath" \
		nnn -gARedQ "$@"

	if [ -r "$NNN_TMPFILE" ]; then
		. "$NNN_TMPFILE"
		rm -f "$NNN_TMPFILE" > /dev/null
	fi
}
