#!/bin/sh

documentsPath=$(xdg-user-dir DOCUMENTS);
downloadsPath=$(xdg-user-dir DOWNLOADS);
moviesPath=$(xdg-user-dir MOVIES);

export NNN_PLUG="p:preview-tui;t:preview-tabbed;n:bulknew;e:preview-tui-ext;c:cleanfilename;m:mtpmount;w:nmount;l:finder"
export NNN_BMS="d:$documentsPath;D:$downloadsPath;s:~/.local/src/;b:~/.local/bin;c:~/C/;C:~/.config/;l:~/.local/share/;u:~/C/university/smi_s4;m:$moviesPath;p:~/projects"
export NNN_TRASH=1
export NNN_OPENER="open"
export NNN_FIFO='/tmp/nnn.fifo'

export NNN_COLORS='#0c020b09;4216'
export NNN_FCOLORS='000b0c0200000600090b0b00'

export NNN_ARCHIVE="\\.(rar)$"


n()
{
    # Block nesting of nnn in subshells
    if [ -n $NNNLVL ] && [ "${NNNLVL:-0}" -ge 1 ]; then
        echo "nnn is already running"
        return
    fi

    # The default behaviour is to cd on quit (nnn checks if NNN_TMPFILE is set)
    # To cd on quit only on ^G, remove the "export" as in:
    #     NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"
    # NOTE: NNN_TMPFILE is fixed, should not be modified
    NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"

    # Unmask ^Q (, ^V etc.) (if required, see `stty -a`) to Quit nnn
    # stty start undef
    # stty stop undef
    # stty lwrap undef
    # stty lnext undef

    nnn -Red "$@"

    if [ -f "$NNN_TMPFILE" ]; then
            . "$NNN_TMPFILE"
            rm -f "$NNN_TMPFILE" > /dev/null
    fi
}
